spring:
  application:
    name: listener-demo

  # RabbitMQ 相关配置项
  rabbitmq:
    host: 192.168.10.99
    port: 5672
    username: admin
    password: admin
    virtual-host: /



server:
  port: ${random.int[10000,19999]} # 随机端口，方便启动多个消费者
