spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 121.196.184.98 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: center # RabbitMQ 服务的账号
    password: 123qwe # RabbitMQ 服务的密码
    publisher-confirm-type: simple # 设置 Confirm 类型为 SIMPLE 。
